# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - 1.12.x

git:
  depth: 1

install: true

notifications:
  email: false

env:
  - GO111MODULE=on
  - CGO=0

before_script:
  - go get ./...

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled
